### ISSUE TITLE
Broken Please Update

### ISSUE THREAD

**Issue by diveyez** [stef/wireless-radar#4] opened 2018-03-18 12:28 UTC
root@base-Rpi3B:~/wireless-radar # ./setup.py
./setup.py: line 2: import: command not found
from: can't read /var/mail/setuptools
./setup.py: line 9: syntax error near unexpected token `('
./setup.py: line 9: `def read(fname):'

**Comment by stef** [comment] 2018-03-18 13:49
duplicate of #3

**Closed as completed by stef** 2018-03-18 13:49 UTC
